version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    networks:
    - my_network

networks:
  my_network:
    driver: bridge